# -*- coding: utf-8 -*-
"""oop in class exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12-Je-PFLdnKHTPikOMw5ee8CTI96TYhR
"""

class Person:
 #constructor
  def __init__(self, name, age, address):
    self.name = name
    self.age = age
    self.address = address

  def get_name(self):
    return 'My name is ' + self.name

  def get_address(self):
    return 'My address is ' + self.address
  
  def get_age(self):
    return 'My age is ' + str(self.age)

  def set_address(self, address):
    self.address = address

  def set_name(self, name):
    self.name = name

  def set_age(self, age):
    self.age = age

#instantiate an object of the person class
p1 = Person('Mike', 22, '2900 Beford Ave')

print(p1.get_name())
print(p1.get_address())
print(p1.get_age())

p1.set_address('123 Ocean Ave')
p1.get_address()

class Employee(Person):
  def __init__(self, name, age, address, title, salary):
    super().__init__(name, age, address)
    self.title = title
    self.salary = salary

  def get_title(self):
    return 'My job title is ' + self.title

  def get_salary(self):
    return 'My salary is ' + str(self.salary)

  def set_title(self, title):
    self.title = title

  def set_salary(self, salary):
    self.salary = salary

e1 = Employee('Alice', 21, '1 Main Street', 'Data Analyst', 130000)

e1.get_name()

e1.set_address('2 Wall Street')

e1.set_title('Data Manager')

e1.get_name()

e1.get_address()

e1.get_title()

e1.get_salary()

class Cat:
  def __init__(self, name, age, breed):
    self.name = name
    self.age = age
    self.breed = breed

  def sound(self):
    return 'meow!'

  def favorite_food(self):
    return 'fish'
    
  def temperament(self):
    return 'cautious'

class Dog:
  def __init__(self, name, age, breed):
    self.name = name
    self.age = age
    self.breed = breed
 
  def sound(self):
    return 'woof!'

  def favorite_food(self):
    return 'bones'

  def temperament(self):
    return 'friendly'

#instantiating objects
c1 = Cat('oscar', 4, 'siamese' )
d1 = Dog('fido', 12, 'beagle')

#printing the cat's sound
print(c1.sound()) #meow

#printing the dog's sound
print(d1.sound()) #woof

#instantiating objects
c1 = Cat('oscar', 4, 'siamese' )

d1 = Dog('fido', 12, 'beagle')

#setting c1 to the d1 object
c1 = d1
print(c1.sound()) #woof is printed

#instantiating objects
c1 = Cat('oscar', 4, 'siamese' )
d1 = Dog('fido', 12, 'beagle')

for pet in (c1,d1):
 print(pet.sound())
 print(pet.favorite_food())
 print(pet.temperament())

